version: "2"
services:

  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host


  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888

  registrationservice:
    image: registration-servcie:latest
    build: registration-service/
    restart: always
    network_mode: host
    ports:
      - 8887:8887
    expose:
      - 8887


  productservice:
    image: product-servcie:latest
    build: ./productService
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8084:8084
    expose:
      - 8084



